### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by anvbey** [anvbey/avatarmeherbabalucknowcentre#12]
- Make it centre and flex-start

- Number of members range should not go below 1

- giving tooltip for wrong submission

- number of members should not change when the input is null

- remove button timeout reduce

- update button to add

**Comment by aryansri-19** [comment]
what is update button?

**Comment by anvbey** [comment]
Whenever you change the number of members there should be an update button just beside the input field and it gets enabled only when the user makes some changes. Whenever the update button is clicked the number of fields should change accordingly and gets disabled

**Comment by aryansri-19** [comment]
> Whenever you change the number of members there should be an update button just beside the input field and it gets enabled only when the user makes some changes. Whenever the update button is clicked the number of fields should change accordingly and gets disabled

but that's exactly what 'continue' is doing
